/** Asset manifest for the office scene: texture key -> public URL. */
export const CHARACTER_COUNT = 6;
export const CHAR_FRAME_W = 16;
export const CHAR_FRAME_H = 32;
export const CHAR_FRAMES_PER_ROW = 7;

/** Furniture textures used by the fixed layout (folder/file under /assets/furniture). */
export const FURNITURE_FILES: Record<string, string> = {
  DESK_FRONT: 'DESK/DESK_FRONT.png',
  DESK_SIDE: 'DESK/DESK_SIDE.png',
  PC_FRONT_ON_1: 'PC/PC_FRONT_ON_1.png',
  PC_FRONT_ON_2: 'PC/PC_FRONT_ON_2.png',
  PC_FRONT_ON_3: 'PC/PC_FRONT_ON_3.png',
  PC_FRONT_OFF: 'PC/PC_FRONT_OFF.png',
  WOODEN_CHAIR_BACK: 'WOODEN_CHAIR/WOODEN_CHAIR_BACK.png',
  WOODEN_CHAIR_FRONT: 'WOODEN_CHAIR/WOODEN_CHAIR_FRONT.png',
  CUSHIONED_CHAIR_BACK: 'CUSHIONED_CHAIR/CUSHIONED_CHAIR_BACK.png',
  BOOKSHELF: 'BOOKSHELF/BOOKSHELF.png',
  DOUBLE_BOOKSHELF: 'DOUBLE_BOOKSHELF/DOUBLE_BOOKSHELF.png',
  WHITEBOARD: 'WHITEBOARD/WHITEBOARD.png',
  LARGE_PAINTING: 'LARGE_PAINTING/LARGE_PAINTING.png',
  SMALL_PAINTING: 'SMALL_PAINTING/SMALL_PAINTING.png',
  CLOCK: 'CLOCK/CLOCK.png',
  PLANT: 'PLANT/PLANT.png',
  PLANT_2: 'PLANT_2/PLANT_2.png',
  LARGE_PLANT: 'LARGE_PLANT/LARGE_PLANT.png',
  CACTUS: 'CACTUS/CACTUS.png',
  SOFA_FRONT: 'SOFA/SOFA_FRONT.png',
  SMALL_TABLE_FRONT: 'SMALL_TABLE/SMALL_TABLE_FRONT.png',
  COFFEE: 'COFFEE/COFFEE.png',
  COFFEE_TABLE: 'COFFEE_TABLE/COFFEE_TABLE.png',
  BIN: 'BIN/BIN.png',
  POT: 'POT/POT.png',
};

export const FLOOR_COUNT = 9;
