// Copies the upstream Pixel Agents PNG assets into town/public/assets so the
// Vite dev server and the built server can serve them from the same path.
// The copy is reproducible: it only ever reads from ../webview-ui/public/assets
// and rewrites town/public/assets from scratch. Provenance is recorded in
// town/docs/assets.md and in the generated ATTRIBUTION.txt next to the copy.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const townRoot = path.resolve(here, '..');
const repoRoot = path.resolve(townRoot, '..');
const source = path.join(repoRoot, 'webview-ui', 'public', 'assets');
const target = path.join(townRoot, 'public', 'assets');

const WANTED = {
  characters: /^char_\d+\.png$/,
  floors: /^floor_\d+\.png$/,
  walls: /^wall_\d+\.png$/,
  carpets: /^carpet_\d+\.png$/,
};

const FURNITURE = [
  'BIN',
  'BOOKSHELF',
  'CACTUS',
  'CLOCK',
  'COFFEE',
  'COFFEE_TABLE',
  'CUSHIONED_BENCH',
  'CUSHIONED_CHAIR',
  'DESK',
  'DOUBLE_BOOKSHELF',
  'HANGING_PLANT',
  'LARGE_PAINTING',
  'LARGE_PLANT',
  'PC',
  'PLANT',
  'PLANT_2',
  'POT',
  'SMALL_PAINTING',
  'SMALL_PAINTING_2',
  'SMALL_TABLE',
  'SOFA',
  'TABLE_FRONT',
  'WHITEBOARD',
  'WOODEN_BENCH',
  'WOODEN_CHAIR',
];

function fail(msg) {
  console.error(`[copy-assets] ${msg}`);
  process.exit(1);
}

if (!fs.existsSync(source)) fail(`source assets not found: ${source}`);

fs.rmSync(target, { recursive: true, force: true });
fs.mkdirSync(target, { recursive: true });

let count = 0;
for (const [dir, pattern] of Object.entries(WANTED)) {
  const from = path.join(source, dir);
  const to = path.join(target, dir);
  fs.mkdirSync(to, { recursive: true });
  for (const name of fs.readdirSync(from)) {
    if (!pattern.test(name)) continue;
    fs.copyFileSync(path.join(from, name), path.join(to, name));
    count++;
  }
}

const furnitureRoot = path.join(target, 'furniture');
fs.mkdirSync(furnitureRoot, { recursive: true });
for (const id of FURNITURE) {
  const from = path.join(source, 'furniture', id);
  if (!fs.existsSync(from)) fail(`furniture folder missing upstream: ${id}`);
  const to = path.join(furnitureRoot, id);
  fs.mkdirSync(to, { recursive: true });
  for (const name of fs.readdirSync(from)) {
    if (!/\.(png|json)$/i.test(name)) continue;
    fs.copyFileSync(path.join(from, name), path.join(to, name));
    count++;
  }
}

const attribution = [
  'Agent Town asset copy',
  '',
  'Every file in this folder is copied verbatim from the upstream Pixel Agents',
  'repository (webview-ui/public/assets) at commit',
  '3537e140c2094761beae748592aeb92ece8edfdd, MIT License, Copyright (c) 2026 Pablo De Lucca.',
  'The six character sheets are based on "Metro City" by JIK-A-4',
  '(https://jik-a-4.itch.io/metrocity-free-topdown-character-pack) as credited in the upstream README.',
  'This folder is regenerated by `npm run assets`; do not edit files here by hand.',
  '',
].join('\n');
fs.writeFileSync(path.join(target, 'ATTRIBUTION.txt'), attribution);

console.log(`[copy-assets] copied ${count} files to ${path.relative(townRoot, target)}`);
